name: store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # repository package
  api_repository:
    path: ./packages/api_repository
  client_repository:
    path: ./packages/client_repository
  user_repository:
    path: ./packages/user_repository
  product_repository:
    path: ./packages/product_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
